---
- name: Add SNMP device to LibreNMS
  when:
    - librenms_device_check.status == 404
  block:
    - name: Add device to LibreNMS - SNMP V3
      delegate_to: localhost
      tags: add
      ansible.builtin.uri:
        url: http://{{ librenms_host }}/api/v0/devices
        headers:
          X-Auth-Token: "{{ librenms_rest_apitoken }}"
        method: POST
        body_format: json
        body:
          hostname: "{{ ansible_host }}"
          snmpver: "{{ snmp_version }}"
          authlevel: "{{ snmp_authlevel }}"
          authname: "{{ snmp_user }}"
          authpass: "{{ snmp_auth_password }}"
          authalgo: "{{ snmp_authalgorithm }}"
          cryptopass: "{{ snmp_encrypt_password }}"
          cryptoalgo: "{{ snmp_crypto_algorithm }}"
          force_add: "{{ librenms_force_add }}"
      when:
        - librenms_device_state is defined
        - librenms_device_state == 'present'
        - snmp_version is defined
        - snmp_version == 'v3'
        - librenms_force_add is defined
        - not librenms_ping_only

    - name: Add device to LibreNMS - SNMP V2c
      delegate_to: localhost
      tags: add
      ansible.builtin.uri:
        url: http://{{ librenms_host }}/api/v0/devices
        headers:
          X-Auth-Token: "{{ librenms_rest_apitoken }}"
        method: POST
        body_format: json
        body:
          hostname: "{{ ansible_host }}"
          snmpver: "{{ snmp_version }}"
          community: "{{ snmp_community }}"
          force_add: "{{ librenms_force_add }}"
      when:
        - librenms_device_state is defined
        - librenms_device_state == 'present'
        - snmp_version is defined
        - snmp_version == 'v2c'
        - librenms_force_add is defined
        - not librenms_ping_only

    - name: Add device to LibreNMS - Ping
      delegate_to: localhost
      tags: add
      ansible.builtin.uri:
        url: http://{{ librenms_host }}/api/v0/devices
        headers:
          X-Auth-Token: "{{ librenms_rest_apitoken }}"
        method: POST
        body_format: json
        body:
          hostname: "{{ ansible_host }}"
          snmp_disable: true
          force_add: "{{ librenms_force_add }}"
      when:
        - librenms_device_state is defined
        - librenms_device_state == 'present'
        - librenms_force_add is defined
        - librenms_ping_only
