--- 
- name: See if device exists in LibreNMS
  block:
  - name: See if device exists in LibreNMS
    delegate_to: localhost
    tags: check
    uri:
        url: http://{{LIBRENMS_HOST}}/api/v0/devices/{{ansible_host}}
        headers:
          X-Auth-Token: "{{LIBRE_REST_APITOKEN}}"
        status_code:
            - 200
            - 404
    when:
      - "LIBRENMS_DEVICE_STATE is defined"
    register: LIBRENMS_DEVICE_CHECK

