---
- name: See if device exists in LibreNMS
  block:
    - name: See if device exists in LibreNMS
      delegate_to: localhost
      tags: check
      ansible.builtin.uri:
        url: http://{{ librenms_host }}/api/v0/devices/{{ ansible_host }}
        headers:
          X-Auth-Token: "{{ libre_rest_apitoken }}"
        status_code:
          - 200
          - 404
      when:
        - "librenms_device_state is defined"
      register: librenms_device_check
