---
- name: Remove device from LibreNMS
  when:
    - librenms_device_check.status == 200
    - librenms_device_state == 'absent'
  block:
    - name: Remove device from LibreNMS
      delegate_to: localhost
      tags: remove
      ansible.builtin.uri:
        url: http://{{ librenms_host }}/api/v0/devices/{{ ansible_host }}
        headers:
          X-Auth-Token: "{{ librenms_rest_apitoken }}"
        method: DELETE
        status_code:
          - 200
          - 400
